# Generated by Django 5.0.14 on 2026-04-06 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentactivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='audioartifact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aurasession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='thoughtlog',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='aurasession',
            name='model_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='aurasession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
