# Generated by Django 5.0.14 on 2026-04-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_session_fk_uuid_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtlog',
            name='interrupted_by',
            field=models.TextField(blank=True, default='', help_text='Partial response that was interrupted (if applicable)'),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='interruption_type',
            field=models.CharField(blank=True, choices=[('user_speech', 'User speech detected'), ('background_noise', 'Background noise (ignored)'), ('not_interrupted', 'Response completed normally')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='thoughtlog',
            name='resumption_context',
            field=models.TextField(blank=True, default='', help_text='How next response pivoted from interruption'),
        ),
    ]
